# Generated by Django 4.0.3 on 2022-03-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auth_user_id',
            new_name='auth_user',
        ),
    ]
