# Generated by Django 4.0.3 on 2022-04-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0003_rename_issue_id_comment_issue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'permissions': [('change_status', 'Can change the status of tasks')]},
        ),
    ]
