# Generated by Django 4.0.3 on 2022-04-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0004_alter_contributor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={},
        ),
    ]
