# Generated by Django 4.0.3 on 2022-03-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0004_alter_issue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='title',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
    ]
