# Generated by Django 4.0.3 on 2022-03-30 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('softdesk', '0005_remove_issue_assignee_remove_issue_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='createur_issue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='createur', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
